from pathlib import Path
import html

ROOT=Path(__file__).parent
sectors=[
('building-construction','Building & Construction','Project backlogs, maintenance needs, and repeat commercial relationships can support durable demand.'),
('communication-media','Communication & Media','Contracted engagements and recurring client relationships can create visible, repeatable economics.'),
('entertainment-recreation','Entertainment & Recreation','Membership, participation, and recurring-use models may produce dependable customer behavior.'),
('financial-services','Financial Services','Recurring revenue and transferable books of business can support continuity beyond the owner.'),
('health-care-fitness','Health Care & Fitness','Defensive demand and recurring service relationships can remain durable through operating cycles.'),
('manufacturing','Manufacturing','Established customer relationships, operating know-how, and tangible assets can support transferability.'),
('online-technology','Online & Technology','Scalable operations and repeat usage can create attractive economics when customer demand is durable.'),
('service-businesses','Service Businesses','Fragmented service categories may offer resilient local demand and thoughtful consolidation potential.'),
('wholesale-distribution','Wholesale & Distributors','Recurring B2B needs and long-standing supplier relationships can underpin stable operating performance.')]
mark='<svg class="brand-mark" viewBox="0 0 36 36" aria-hidden="true"><path d="M7 5v26M29 5v26M7 18h22"/><path d="M11 5v9M25 22v9" stroke-opacity=".45"/></svg>'
arrow='<span class="arrow" aria-hidden="true">↗</span>'
def header(page):
  active=' aria-current="page"' if page=='acquire' else ''
  return f'''<a class="skip" href="#main">Skip to content</a>
  <header class="header"><div class="wrap header-inner">
    <a class="brand" href="index.html" aria-label="Hyperboards home">{mark}<span>Hyperboards</span></a>
    <button class="menu-button" type="button" aria-expanded="false" aria-controls="navigation" data-menu>Menu <span aria-hidden="true">+</span></button>
    <nav class="nav" id="navigation" aria-label="Primary navigation" data-navigation><a href="index.html#approach">Why Hyperboards</a><a href="what-we-acquire.html"{active}>What we acquire</a><a href="index.html#process">Our process</a><a href="index.html#questions">Questions</a></nav>
    <a class="header-cta" href="sell-your-business.html">Start a conversation {arrow}</a>
  </div></header>'''
def footer():
  return f'''<footer class="footer"><div class="wrap"><div class="footer-grid">
    <div><a class="brand" href="index.html">{mark}<span>Hyperboards</span></a><p>We buy established businesses directly from their owners.</p></div>
    <div><div class="footer-label">Explore</div><div class="footer-links"><a href="what-we-acquire.html">What we acquire</a><a href="index.html#approach">Our approach</a><a href="index.html#process">The acquisition process</a><a href="index.html#questions">Common questions</a></div></div>
    <div><div class="footer-label">Start a conversation</div><div class="footer-links"><a href="sell-your-business.html">For business owners ↗</a><a href="mailto:hello@hyperboards.com?subject=Investor%20relationship">Investor relationships ↗</a><a href="mailto:hello@hyperboards.com">hello@hyperboards.com</a></div></div>
  </div><div class="footer-bottom"><span>© <span data-year>2026</span> Hyperboards</span><span>Direct relationships. Considered ownership.</span><div class="footer-legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></div></footer>'''
def page(name,title,description,body,kind='home'):
  output=f'''<!doctype html><html lang="en" data-design="meridian"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0a0e15"><meta name="description" content="{description}"><title>{title} | Hyperboards</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='5' fill='%230d1729'/%3E%3Cpath d='M8 6v20M24 6v20M8 16h16' stroke='%23bed8ff' stroke-width='2'/%3E%3C/svg%3E"><link rel="preload" href="assets/instrument-sans.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head><body>{header(kind)}<main id="main">{body}</main>{footer()}</body></html>'''
  (ROOT/name).write_text(output,encoding='utf-8')
def closing(title='The next chapter<br>starts with <em>a conversation.</em>'):
  return f'''<section class="closing"><div class="reveal"><div class="eyebrow">A private first step</div><h2>{title}</h2><p>You have built something worth understanding. We would welcome a direct introduction.</p><a class="button button-primary" href="sell-your-business.html">Discuss your business {arrow}</a></div></section>'''
def profile():
  return '''<div class="profile-grid"><article class="profile-panel reveal"><div class="eyebrow">01 / Target annual EBITDA</div><strong>$750K–$2M</strong><p>Consistent, supportable earnings with a clear view of what drives performance.</p></article><article class="profile-panel reveal"><div class="eyebrow">02 / Typical deal value</div><strong>$2M–$6M</strong><p>Value depends on earnings quality, business context, transaction structure, and diligence.</p></article></div><div class="profile-foot"><p class="small-note">Ranges are acquisition guidelines, not a valuation, financing commitment, or offer. Every opportunity is considered on its own facts.</p><a class="text-link" href="sell-your-business.html">Discuss potential fit <span aria-hidden="true">↗</span></a></div>'''
def sector_explorer():
  buttons=''.join(f'<li><button class="sector-choice" type="button" data-sector="{slug}" data-number="{i:02d}" data-title="{html.escape(title)}" data-rationale="{html.escape(copy)}" aria-pressed="{str(i==1).lower()}" aria-controls="sector-context"><span>{i:02d}</span><b>{html.escape(title)}</b><i aria-hidden="true">↗</i></button></li>' for i,(slug,title,copy) in enumerate(sectors,1))
  fallback=''.join(f'<dt>{html.escape(title)}</dt><dd>{html.escape(copy)}</dd>' for _,title,copy in sectors)
  return f'''<div data-sector-explorer><div class="sector-layout"><ol class="sector-list">{buttons}</ol><aside class="sector-detail" id="sector-context" aria-label="Selected industry context"><div class="eyebrow">The demand behind the business</div><span class="sector-no" data-sector-number aria-hidden="true">01</span><div aria-live="polite" aria-atomic="true"><h3 data-sector-title>Building &amp; Construction</h3><p data-sector-copy>{sectors[0][2]}</p></div><a class="text-link" href="sell-your-business.html?industry=building-construction" data-sector-link>Discuss a business in this sector {arrow}</a></aside></div><p class="small-note sector-note">Industry is a starting point. Sector inclusion does not imply fit; every business must satisfy the full acquisition and underwriting criteria.</p><details class="sector-fallback"><summary>Read all industry demand explanations</summary><dl>{fallback}</dl></details></div>'''
home=f'''
<section class="hero" aria-labelledby="hero-title"><div class="wrap"><div class="hero-grid">
  <div class="hero-copy"><p class="eyebrow">Private business acquisitions</p><h1 id="hero-title">Built by you.<br>Ready for<br><em>what’s next.</em></h1><p class="hero-lede">A direct buyer for the business you built. We acquire established, profitable companies with care for what makes them work.</p><div class="actions"><a class="button button-primary" href="sell-your-business.html">Let’s start a conversation {arrow}</a><a class="text-link" href="what-we-acquire.html">Our acquisition focus <span aria-hidden="true">→</span></a></div><p class="hero-caption"><span class="status-dot" aria-hidden="true"></span>Private. Direct. No obligation to proceed.</p></div>
  <div class="art-stage" data-art-stage aria-hidden="true"><div class="art-float"><img class="art-object" src="assets/continuity.webp" alt="" width="1100" height="1100" fetchpriority="high"></div><span class="art-label">A connection built for continuity</span></div>
  <button class="motion-toggle" type="button" data-motion-toggle aria-pressed="false"><span aria-hidden="true">Ⅱ</span>Pause motion</button>
</div><div class="hero-bottom"><div><strong>$750K–$2M</strong><p>Target annual<br>EBITDA</p></div><div><strong>$2M–$6M</strong><p>Typical<br>deal value</p></div><div><p class="profile-note">Established, profitable businesses.<br>Ranges are guidelines, not valuations or offers.</p></div></div></div></section>

<section class="section" id="approach"><div class="wrap"><div class="manifesto reveal"><p class="eyebrow">A direct relationship</p><div><h2>One conversation.<br>The actual buyer.<br><span>A more considered next step.</span></h2><div class="manifesto-copy"><p>You have spent years building your business. Exploring its future should begin with someone who wants to understand it.</p><p>Hyperboards evaluates each opportunity as the prospective acquirer. We are not a broker, investment bank, or adviser marketing your company to third-party buyers.</p></div></div></div><div class="principles">
<article class="principle reveal"><span>01 / CONNECTION</span><h3>Direct engagement</h3><p>Talk with the party considering the purchase, from the first introduction onward.</p></article><article class="principle reveal"><span>02 / DISCRETION</span><h3>A private beginning</h3><p>Focused conversations while both sides decide whether there is enough alignment to continue.</p></article><article class="principle reveal"><span>03 / TRANSITION</span><h3>Room for your goals</h3><p>Your role, timing, and potential structure are considered in the context of your company.</p></article><article class="principle reveal"><span>04 / CONTINUITY</span><h3>Respect for what works</h3><p>Start with the people, relationships, and practices that give the business its strength.</p></article>
</div></div></section>

<section class="section acquisition" id="profile"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">What we acquire</p><h2>Substance today.<br><em>Possibility tomorrow.</em></h2></div><p>Established companies with durable demand, understandable economics, and operations that can transfer beyond the current owner.</p></div>{profile()}<div class="sector-section" id="industries"><div class="section-heading reveal"><div><p class="eyebrow">Our industry focus</p><h2>Different businesses.<br>A common foundation.</h2></div><p>Nine sectors where repeat demand and enduring customer relationships can create a basis for long-term ownership. Select an industry to explore.</p></div>{sector_explorer()}</div></div></section>

<section class="section process" id="process"><div class="wrap"><div class="process-top reveal"><div><p class="eyebrow">From introduction to understanding</p><h2>Progress with purpose.<br><em>At every stage.</em></h2></div><p>A business should be understood before terms are finalized. Detail builds as mutual interest grows, with a direct conversation throughout.</p></div><ol class="process-steps"><li class="reveal"><span class="step-no">01 / BEGIN</span><h3>Confidential introduction</h3><p>Share the broad outline of the business and what is prompting the conversation.</p></li><li class="reveal"><span class="step-no">02 / ALIGN</span><h3>Initial<br>fit</h3><p>We compare the opportunity with our acquisition profile and your priorities.</p></li><li class="reveal"><span class="step-no">03 / UNDERSTAND</span><h3>Business<br>review</h3><p>With mutual interest, we explore earnings, operations, customer relationships, and context.</p></li><li class="reveal"><span class="step-no">04 / CONSIDER</span><h3>Terms &amp;<br>diligence</h3><p>Potential structure, verification, documentation, and approvals are worked through directly.</p></li></ol></div></section>

<section class="section"><div class="wrap stewardship"><figure class="steward-art reveal"><img src="assets/continuity.webp" width="1100" height="1100" loading="lazy" alt="Interlocking silver forms, a study in continuity"><figcaption><span>THE STRENGTH OF WHAT CONNECTS US</span><span>H / 01</span></figcaption></figure><div class="steward-copy reveal"><p class="eyebrow">Beyond the transaction</p><h2>Good ownership<br>begins with<br><em>understanding.</em></h2><p>A company is more than its financial statements. It is the reputation, judgment, and everyday commitments built over years.</p><ul class="steward-list"><li><strong>People</strong><span>Understand the team and leadership context.</span></li><li><strong>Customers</strong><span>Respect the relationships behind repeat demand.</span></li><li><strong>Continuity</strong><span>Preserve the practices that make the company work.</span></li><li><strong>Context</strong><span>Make decisions grounded in operating reality.</span></li></ul></div></div></section>

<section class="section section-rule" id="questions"><div class="wrap faq-layout"><div class="faq-intro reveal"><p class="eyebrow">Common questions</p><h2>A clearer<br><em>starting point.</em></h2><p>A first conversation can answer practical questions without creating pressure to proceed.</p></div><div class="faq-items reveal"><details><summary>Do I need to be actively selling my business?</summary><p>No. Many conversations begin while an owner is still considering timing and alternatives. You do not need a final decision to introduce yourself.</p></details><details><summary>Is the first conversation confidential?</summary><p>We intend to handle introductions discreetly. Highly sensitive documents should wait until appropriate protections and a secure process are in place. An introduction alone does not create an NDA.</p></details><details><summary>What role can I have after a transaction?</summary><p>That depends on your goals and the company’s needs. A transition may involve an immediate handoff, a defined transition period, or a continuing role.</p></details><details><summary>Are the financial ranges absolute?</summary><p>No. The $750K–$2M target EBITDA and $2M–$6M typical deal value are current acquisition guidelines. Every company is evaluated on its specific facts, and these ranges are not a valuation or offer.</p></details><details><summary>Is Hyperboards a broker or adviser?</summary><p>No. Hyperboards evaluates opportunities as the prospective buyer. We do not market your business to third-party acquirers or run a sale process on your behalf.</p></details></div></div></section>
{closing()}
'''
page('index.html','A considered next chapter','Hyperboards buys established, profitable businesses directly from owners. Explore a considered next chapter for the business you built.',home)

fits=[('Recurring or repeat customers','Revenue supported by enduring needs, contracted relationships, subscriptions, maintenance, or dependable repeat purchasing.'),('Defensible earnings','Healthy economics, understandable adjustments, sensible capital needs, and a track record that can be responsibly underwritten.'),('Transferable capability','A capable team, documented routines, and durable relationships, with knowledge that can survive a transition.'),('Clear market relevance','Niche expertise, a useful reputation, attractive local density, or another practical reason customers continue to choose the business.'),('A responsible transition','An owner willing to share context and help define a handover that respects the people and relationships behind the company.'),('Room for considered growth','Potential to improve systems, expand responsibly, or strengthen the business while preserving what already works.')]
fit_articles=''.join(f'<article class="reveal"><span>{i:02d}</span><div><h3>{title}</h3><p>{copy}</p></div></article>' for i,(title,copy) in enumerate(fits,1))
acquire=f'''
<section class="page-hero"><div class="wrap"><p class="eyebrow">Our acquisition mandate</p><h1>Built to last.<br><em>Ready to carry forward.</em></h1><div class="page-hero-bottom"><p>We look for established, profitable companies with durable demand. Businesses whose customers, people, and operating strengths can support thoughtful long-term ownership.</p><aside class="page-hero-aside"><strong>A direct prospective buyer.</strong><p>We evaluate each opportunity for ourselves. Hyperboards is not a broker, investment bank, or M&amp;A adviser representing another party.</p></aside></div></div></section>
<section class="section" id="profile"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">Our current focus</p><h2>Clear parameters.<br><em>Individual consideration.</em></h2></div><p>The numbers begin a conversation. Earnings quality, the business model, and the owner’s goals determine whether there is a fit.</p></div>{profile()}</div></section>
<section class="section acquisition" id="characteristics"><div class="wrap fit-layout"><div class="fit-heading reveal"><p class="eyebrow">What tends to fit</p><h2>The strength<br>beneath<br><em>the numbers.</em></h2><p>We look at the business as a whole: how it earns, why customers return, and what enables it to continue.</p></div><div class="fit-items">{fit_articles}</div></div></section>
<section class="section" id="industries"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">Nine areas of focus</p><h2>Durable demand.<br><em>Across industries.</em></h2></div><p>Sector fit is only the beginning. Select an industry to see the demand patterns that may align with our acquisition criteria.</p></div>{sector_explorer()}<aside class="exclusions reveal"><strong>Outside our current mandate</strong><p>Agriculture; automotive and boats; beauty and personal care; education and children; pet services; restaurants and food; retail; transportation and storage; and travel.</p></aside></div></section>
{closing('A business that fits.<br><em>A conversation worth having.</em>')}
'''
page('what-we-acquire.html','What we acquire','Explore the Hyperboards acquisition profile: $750K–$2M target EBITDA, $2M–$6M typical deal value, and nine industry sectors.',acquire,'acquire')

options=''.join(f'<option value="{slug}">{html.escape(title)}</option>' for slug,title,_ in sectors)
sell=f'''
<section class="page-hero"><div class="wrap"><p class="eyebrow">A confidential first step</p><h1>Your business.<br>Your timing.<br><em>Let’s talk about both.</em></h1><div class="page-hero-bottom"><p>You do not need a sale book, a broker, or a final decision. A short introduction is enough to begin a direct conversation with the prospective buyer.</p><aside class="page-hero-aside"><strong>Private. Direct. Without pressure.</strong><p>Share broad information first. Sensitive records can wait until there is mutual interest and appropriate protection.</p></aside></div></div></section>
<section class="form-page" id="owner-introduction"><div class="wrap form-layout"><form class="owner-form" action="/api/inquiries" method="post" data-owner-form aria-labelledby="form-title"><p class="eyebrow">Owner introduction</p><h2 id="form-title">Start with the broad outline.</h2><p class="form-intro">Fields marked * are required for an initial fit review. Submitting this form does not create an NDA, valuation, offer, or obligation for either party.</p><div class="form-grid">
<div class="field"><label for="fullName">Your name *</label><input id="fullName" name="fullName" autocomplete="name" minlength="2" maxlength="100" required></div>
<div class="field"><label for="email">Email address *</label><input id="email" name="email" type="email" autocomplete="email" maxlength="200" required></div>
<div class="field"><label for="phone">Phone <small>(optional)</small></label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="40"></div>
<div class="field"><label for="company">Company name *</label><input id="company" name="company" autocomplete="organization" minlength="2" maxlength="120" required></div>
<div class="field"><label for="companyWebsite">Company website <small>(optional)</small></label><input id="companyWebsite" name="companyWebsite" type="url" autocomplete="url" placeholder="https://" maxlength="240"></div>
<div class="field"><label for="location">Business location *</label><input id="location" name="location" autocomplete="address-level2" minlength="2" maxlength="120" required></div>
<div class="field"><label for="industry">Industry *</label><select id="industry" name="industry" required><option value="">Select an industry</option>{options}<option value="other">Other</option></select></div>
<div class="field"><label for="ebitda">Approximate annual EBITDA *</label><select id="ebitda" name="ebitda" required><option value="">Select a range</option><option value="under-750k">Under $750K</option><option value="750k-1m">$750K–$1M</option><option value="1m-2m">$1M–$2M</option><option value="over-2m">Over $2M</option><option value="not-sure">Not sure / prefer to discuss</option></select></div>
<fieldset class="form-fieldset"><legend>I am contacting Hyperboards as *</legend><div class="role-choices"><label><input type="radio" name="role" value="owner" required>Business owner</label><label><input type="radio" name="role" value="adviser">Owner’s adviser</label><label><input type="radio" name="role" value="investor">Investor</label><label><input type="radio" name="role" value="other">Other</label></div></fieldset>
<div class="field field-wide"><label for="message">What are you considering? *</label><textarea id="message" name="message" minlength="20" maxlength="4000" required aria-describedby="message-hint"></textarea><small id="message-hint">A short overview of the business, your timing, and what prompted you to reach out is enough. Please write at least 20 characters.</small></div>
<label class="check-field"><input type="checkbox" name="acknowledgement" value="true" required><span>I understand this introduction is not an NDA or an offer, and I will not include confidential customer, employee, or proprietary records. *</span></label>
<div class="honeypot" aria-hidden="true"><label for="companyFax">Company fax</label><input id="companyFax" name="companyFax" tabindex="-1" autocomplete="off"></div>
<div class="form-actions"><button class="button button-primary" type="submit">Send private introduction {arrow}</button><p class="form-status" data-form-status role="status" aria-live="polite">We only request information needed for an initial fit review.</p><noscript><p class="small-note">This form needs the published Hyperboards server to send. You can also email hello@hyperboards.com.</p></noscript></div></div></form>
<aside class="form-rail" aria-label="Conversation details"><div class="rail-top"><p class="eyebrow">A considered beginning</p><h3>Good conversations<br>start with<br><em>understanding.</em></h3><p>We begin with your goals, the broad shape of the business, and whether our acquisition profile may align.</p></div><ol class="rail-steps"><li>Share a short introduction</li><li>Explore potential alignment</li><li>Agree on the next step together</li></ol><div class="email-card"><p>Prefer to write from your inbox?</p><a class="text-link" href="mailto:hello@hyperboards.com?subject=Confidential%20business%20conversation">hello@hyperboards.com {arrow}</a><p class="small-note">Please keep the first introduction to broad information. Sensitive records can wait until appropriate protections are in place.</p></div><div class="form-mark" aria-hidden="true"></div></aside>
</div></section>
'''
page('sell-your-business.html','Discuss your business','Begin a private, direct, no-obligation conversation with Hyperboards about the future of your business.',sell,'sell')
